name: "ğŸ”¤ Lint"

on:
  push:
    branches:
      - master
      - add-ogc-wps-api-on-php
  pull_request:
    branches:
      - master

jobs:
  php-cs-fixer:
    name: "ğŸ˜ PHP-CS-Fixer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "PHP-CS-Fixer"
        uses: docker://oskarstark/php-cs-fixer-ga:3.8.0
        with:
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes --dry-run --diff -- wps

  eslint:
    name: "ğŸ”¶ EsLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run eslint
